export default [
  {
    id: 'more_fingers',
    name: 'More Fingers',
    desc: 'Increases points per click by 0.5.',
    icon: '🖐️',
    cost: 50,
    type: 'more_fingers',
    effectType: 'addPPCFraction',
    effectAmount: 0.5,
    max: 20,
    amountOwned: 0,
    costScale: 1.7,
    initialCost: 50,
  },
  {
    id: 'click',
    name: 'Fitte Power',
    desc: 'Increase points per click by 1.',
    icon: '🍑',
    cost: 100,
    type: 'click',
    effectType: 'addPPC',
    effectAmount: 1,
    max: 10,
    amountOwned: 0,
    costScale: 1.7,
    initialCost: 100,
  },
  {
    id: 'auto',
    name: 'Auto Clicker',
    desc: 'Automatically clicks every second.',
    icon: `https://res.cloudinary.com/di8fs1bcm/image/upload/v1748192218/autoclicker_h5wxky.png`,
    cost: 200,
    type: 'auto',
    effectType: 'addAuto',
    effectAmount: 1,
    amountOwned: 0,
    max: 25,
    costScale: 1.8,
    initialCost: 200,
  },
    {
    id: 'mega_click',
    name: 'Mega Fitte Power',
    desc: '',
    icon: '💥',
    cost: 500,
    type: 'mega_click',
    effectType: 'addPPC',
    effectAmount: 5,
    amountOwned: 0,
    max: 5,
    unlocksAfter: { id: 'click', count: 10 },
    costScale: 2,
    initialCost: 500,
  },
{
  id: 'crit_clicks',
  name: 'Critical Clicks',
  desc: 'Chance for a click to give double points.',
  icon: '🎯',
  cost: 1000,
  type: 'crit',
  effectType: 'addCritChance',
  effectAmount: 0.01, // 5% per upgrade
  max: 10,
  amountOwned: 0,
  costScale: 2,
  initialCost: 1000,
},
{
  id: 'double_tap',
  name: 'Double Tap',
  desc: 'Occasionally clicks twice per click.',
  icon: '👆',
  cost: 750,
  type: 'double_tap',
  effectType: 'addPPCFraction',
  effectAmount: 0.5, // Treated as chance-based boost
  amountOwned: 0,
  max: 5,
  costScale: 1.9,
  initialCost: 750,
},


];
