"""add unlocked field to user_achievements

Revision ID: 0d09ec62d04a
Revises: b1014688282c
Create Date: 2025-05-24 11:17:17.903805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d09ec62d04a'
down_revision = 'b1014688282c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_column('unlocked')

    # ### end Alembic commands ###
