"""Add login streak and last login date to User

Revision ID: 0fe4f1eabc2f
Revises: 0d09ec62d04a
Create Date: 2025-05-24 12:10:24.797948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe4f1eabc2f'
down_revision = '0d09ec62d04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login_date')

    # ### end Alembic commands ###
