"""Add rarity and glow_color to ShopItem

Revision ID: 15c7f5b7d655
Revises: 475fa1f4ba08
Create Date: 2025-05-02 22:23:58.832617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c7f5b7d655'
down_revision = '475fa1f4ba08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('glow_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_column('glow_color')
        batch_op.drop_column('rarity')

    # ### end Alembic commands ###
