"""add shop_items table

Revision ID: 3e6816bac9b8
Revises: 125e3ef20c02
Create Date: 2025-04-27 20:11:42.291387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6816bac9b8'
down_revision = '125e3ef20c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('type', sa.Enum('badge', 'theme', name='shop_item_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_items')
    # ### end Alembic commands ###
