"""Add Changelog model

Revision ID: 475fa1f4ba08
Revises: b90456c7ead7
Create Date: 2025-05-01 19:05:17.588999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475fa1f4ba08'
down_revision = 'b90456c7ead7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('added', sa.Text(), nullable=True),
    sa.Column('changed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changelog')
    # ### end Alembic commands ###
