"""Add ondelete cascade to user_shop_items

Revision ID: 7d762b9301e2
Revises: 15c7f5b7d655
Create Date: 2025-05-02 22:51:41.612584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d762b9301e2'
down_revision = '15c7f5b7d655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_shop_items', schema=None) as batch_op:
        batch_op.drop_constraint('user_shop_items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop_items', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_shop_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_shop_items_ibfk_1', 'shop_items', ['item_id'], ['id'])

    # ### end Alembic commands ###
