"""add daily_claim_count to user

Revision ID: b1014688282c
Revises: bc826f38e59c
Create Date: 2025-05-24 11:08:51.735146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1014688282c'
down_revision = 'bc826f38e59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_claim_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_claim_count')

    # ### end Alembic commands ###
