"""Add last_daily_reward_claim to User

Revision ID: b6295bbb3669
Revises: 948b2ce5777f
Create Date: 2025-05-08 20:31:56.545737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6295bbb3669'
down_revision = '948b2ce5777f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_reward_claim', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_daily_reward_claim')

    # ### end Alembic commands ###
