"""Add condition_type and condition_value to Achievement

Revision ID: bc826f38e59c
Revises: e46d85c1d10c
Create Date: 2025-05-24 10:26:32.175427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc826f38e59c'
down_revision = 'e46d85c1d10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('condition_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('condition_value')
        batch_op.drop_column('condition_type')

    # ### end Alembic commands ###
