"""Add achievements table

Revision ID: e46d85c1d10c
Revises: 8b32c27f7e55
Create Date: 2025-05-24 10:13:14.383365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46d85c1d10c'
down_revision = '8b32c27f7e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('glow_color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_constraint('user_achievements_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'achievements', ['achievement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_achievements_ibfk_1', 'shop_items', ['achievement_id'], ['id'])

    op.drop_table('achievements')
    # ### end Alembic commands ###
