"""Change icon column to Text for shop_items

Revision ID: ed856887bb51
Revises: 83c7b5f27092
Create Date: 2025-05-03 22:47:37.481470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed856887bb51'
down_revision = '83c7b5f27092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
